version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - "./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/html"
    ports:
      - "1101:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    restart: always
    depends_on:
      - test.php
      - test.mysql
    networks:
      - test
  test.php:
    image: jiridomjen/etyka-php-fpm-7.4:latest
    restart: always
    volumes:
      - "./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www/html"
    networks:
      - test
  test.mysql:
    networks:
      - test
    ports:
      - 1102:3306

networks:
  test:
    driver: bridge
